In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv(r"housing.csv") 
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [13]:
df1 = df.dropna()
df1.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.7+ MB


In [16]:
df1.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20433.000000  20433.000000        20433.000000  20433.000000   
mean    -119.570689     35.633221           28.633094   2636.504233   
std        2.003578      2.136348           12.591805   2185.269567   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1450.000000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.720000           37.000000   3143.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20433.000000  20433.000000   20433.000000   
mean       537.870553   1424.946949    499.433465       3.871162   
std        421.385070   1133.208490    382.299226       1.899291   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563700   
50%        435.000000   1166.000000    409.000000       3.536500   
75%        647.000000   1722.000000    604.000000       4.744000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20433.000000  
mean        206864.413155  
std         115435.667099  
min          14999.000000  
25%         119500.000000  
50%         179700.000000  
75%         264700.000000  
max         500001.000000

In [22]:
df1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

       ocean_proximity  
0        259279.292070  
1        259279.292070  
2        259279.292070  
3        259279.292070  
4        259279.292070  
...                ...  
20635    124896.863147  
20636    124896.863147  
20637    124896.863147  
20638    124896.863147  
20639    124896.863147  

[20433 rows x 10 columns]

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler() 
df2 = pd.DataFrame(scaler.fit_transform(df1),columns = df1.columns) 
df2

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       0.211155  0.567481            0.784314     0.022331        0.019863   
1       0.212151  0.565356            0.392157     0.180503        0.171477   
2       0.210159  0.564293            1.000000     0.037260        0.029330   
3       0.209163  0.564293            1.000000     0.032352        0.036313   
4       0.209163  0.564293            1.000000     0.041330        0.043296   
...          ...       ...                 ...          ...             ...   
20428   0.324701  0.737513            0.470588     0.042296        0.057883   
20429   0.312749  0.738576            0.333333     0.017676        0.023122   
20430   0.311753  0.732200            0.313725     0.057277        0.075109   
20431   0.301793  0.732200            0.333333     0.047256        0.063315   
20432   0.309761  0.725824            0.294118     0.070782        0.095438   

       population  households  median_income  median_house_value  \
0        0.008941    0.020556       0.539668            0.902266   
1        0.067210    0.186976       0.538027            0.708247   
2        0.013818    0.028943       0.466028            0.695051   
3        0.015555    0.035849       0.354699            0.672783   
4        0.015752    0.042427       0.230776            0.674638   
...           ...         ...            ...                 ...   
20428    0.023599    0.054103       0.073130            0.130105   
20429    0.009894    0.018582       0.141853            0.128043   
20430    0.028140    0.071041       0.082764            0.159383   
20431    0.020684    0.057227       0.094295            0.143713   
20432    0.038790    0.086992       0.130253            0.153403   

       ocean_proximity  
0              0.52587  
1              0.52587  
2              0.52587  
3              0.52587  
4              0.52587  
...                ...  
20428          0.00000  
20429          0.00000  
20430          0.00000  
20431          0.00000  
20432          0.00000  

[20433 rows x 10 columns]

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
y = df2["median_house_value"] 
x = df2.drop("median_house_value",axis = 1) 

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 1) 
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((14303, 9), (14303,), (6130, 9), (6130,))

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [29]:
x_pred = model.predict(x_train)
y_pred = model.predict(x_test)  
x_pred

array([0.28387822, 0.13534316, 0.46406759, ..., 0.73856033, 0.22301705,
       0.36142174])

In [30]:
y_pred

array([0.75367951, 0.54648394, 0.29556861, ..., 0.1594104 , 0.38712287,
       0.49160149])

In [31]:
model.coef_

array([-0.55214682, -0.50578279,  0.10736662, -0.46844117,  1.30384261,
       -2.71123198,  0.57605975,  1.1654101 ,  0.16907316])

In [32]:
model.intercept_

0.4247615059275732

In [33]:
model.score(x_test,y_test) 

0.6575046352886071